### ISSUE TITLE
[Feature Request] Localization

### ISSUE THREAD

**Issue by crhbetz** [sebastienvercammen/devkat-rm-node-webserver#3]
RocketMap supports different locales, for example setting "de" (German) in the config.ini. This will translate Pokemon names, rarity level etc. to the selected language when viewing RocketMap.

However when using devkat-rm-node-webserver to serve data instead of flask, that information is displayed in English in RocketMap.

It would be great if the same localization option could be made available in devkat-rm-node-webserver!

**Comment by sebastienvercammen** [comment]
@crhbetz The problem is that localization of Pokémon data happens on RM's back-end (Flask) rather than on the front-end (turning Pokémon IDs into their names/moves).

A localization rework is planned on RM, which will fix this problem and fix full localization support on RM rather than the partial support we have right now.

Once this is done, localization in the devkat webserver can also be removed.
